name: Twitch Sentiment Bot CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # Add other Node.js versions if needed

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

      
    - name: Check TypeScript compilation
      run: npm run build

    - name: Run tests
      run: npm test
      env:
        # Environment variables for testing
        BOT_USERNAME: test_bot
        OAUTH_TOKEN: mock_token
        CHANNELS: test_channel