name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 10:00 AM UTC
    - cron: '0 10 * * 1'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Update dependencies
        id: update
        run: |
          # Update package-lock.json
          npm update
          
          # Check if there are any changes
          if git diff --quiet package-lock.json; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests after update
        if: steps.update.outputs.no_changes == 'false'
        run: |
          npm ci
          npm run build
          npm test
        env:
          BOT_USERNAME: test_bot
          OAUTH_TOKEN: mock_token
          CHANNELS: test_channel

      - name: Create Pull Request
        if: steps.update.outputs.no_changes == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update npm dependencies'
          title: 'chore: weekly dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated updates to npm dependencies.
            
            ### Changes
            - Updated package-lock.json with latest compatible versions
            - All tests pass with updated dependencies
            
            ### Verification
            - [x] Build passes
            - [x] Tests pass
            - [x] No breaking changes detected
            
            This PR was created automatically by the dependency update workflow.
          branch: chore/dependency-updates
          delete-branch: true
          base: main

  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Check for security vulnerabilities
        run: |
          npm audit --audit-level=high --json > audit-results.json || true
          
          # Check if there are high/critical vulnerabilities
          if npm audit --audit-level=high; then
            echo "No high/critical vulnerabilities found"
          else
            echo "Security vulnerabilities detected - check audit results"
            cat audit-results.json
          fi

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: security-audit-results
          path: audit-results.json
          retention-days: 30